travis:
  secure:
    BINSTAR_TOKEN: ItQeBVoNgphsW+H4LG+SV/dgaxXP8rvOlWQgyEr0IoTBqhAaCefEnEFBMdqixVbfh+XwbVe2H7weWeky68j53Ml4EgjER1feO2hX2AAuXNi4FwCl7cjjf9yGFMpbTTlRq7IsQzLfX8jGRWT7pn82NGvovAn16SePL7hfEaavGnXQ0EhgusfCxExDM2hT8uNu6K2y82MrypRfQ13nI35aUo/rFYaASdp7oXUw2Tf1aW1rBnP9Ge61g1MLavjpkv1+xgdruxccB4FgtWzJ6owXEFemHGJerR5ts0sn4trTR8JttORxEQMYETJqqyQ09opyUbQKY9xvNXOQQUA50TPMzWEAFbWIHZ0iIUnmIRStpEj0q1wt7yWntC7WPAoNj2yHVvtUXW/enPRBQ+tWu6B6I3K7TnxEPyZs8/MNvitYPziEbJG9Sw2D/lSUj1+oK6i6RhtwFc1UVxvwnzW/ts5B69sk1kUxXFpbXhKden1Q07d/JFbPxtbOLGXKMEH1jQVRcF1/aftDu36xHaMYIC4cmBlDRI36PR+hlboSxJYUo+iPN2NammNch30tRLODdk3naiH1F30TQEFwAXwqrjTlLsfcBHL1OyCa3w2GqzZ88AMWXi3BY58UouJ6rnQO4WDoXNhlMSrWkeQaw3iIC/9okRvPPaVE+2uhhpxhhrOwcas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
